"""
Synthetic clinical encounter generator.

Two ideas make this work:

1. BACKWARDS GENERATION. We define the correct SOAP note FIRST (from a fixed set
   of clinical scenarios with known ICD codes), then generate the conversation
   that would have produced it. Because the transcript is built from the note,
   the (transcript -> gold note) pairing is correct by construction and needs no
   hand-labeling. This gives us an authoritative gold set for free.

2. KNOWN PHI INJECTION. Faker produces the fake identities, and we KEEP the exact
   values we injected. That lets the eval measure redaction recall and output
   leakage exactly, because we know precisely what PHI is present in each case.

In production the conversation text would be generated by an LLM for richer,
messier dialogue. Here we template it deterministically (seeded) so the demo is
reproducible and runs with no API. The *structure* — note-first, known PHI,
gold pairing — is identical to the LLM version.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field

from faker import Faker


# --- Scenario bank: each carries its own gold SOAP content + true ICD code. ---
# The note is the source of truth; the conversation is derived from it.

SCENARIOS = [
    {
        "code": "J06.9",
        "subjective": "Reports sore throat, nasal congestion, and cough for three days with a low-grade fever.",
        "objective": ["Temp 100.2F", "Pharynx erythematous", "No tonsillar exudate"],
        "assessment": "Acute viral upper respiratory infection.",
        "plan": ["Rest and increase fluids", "Acetaminophen for fever", "Return if symptoms worsen or persist beyond 10 days"],
        "medications": [{"name": "Acetaminophen", "dose": "500 mg", "frequency": "every 6 hours as needed"}],
        "cc": ("sore throat", "stuffy nose and a cough", "for about three days", "a bit of a fever"),
    },
    {
        "code": "I10",
        "subjective": "Here for blood pressure follow-up. Denies headache or chest pain. Reports occasional missed medication doses.",
        "objective": ["BP 148/92", "Heart rate 78", "No peripheral edema"],
        "assessment": "Essential hypertension, suboptimally controlled.",
        "plan": ["Reinforce medication adherence", "Continue lisinopril", "Recheck blood pressure in four weeks", "Reduce dietary sodium"],
        "medications": [{"name": "Lisinopril", "dose": "10 mg", "frequency": "once daily"}],
        "cc": ("blood pressure check", "no headaches or chest pain", "for the follow-up", "I sometimes forget my pill"),
    },
    {
        "code": "E11.9",
        "subjective": "Diabetes follow-up. Reports increased thirst and fatigue over the past month. Adherent to metformin.",
        "objective": ["Fasting glucose 168 mg/dL", "HbA1c 8.1%", "Feet without ulceration"],
        "assessment": "Type 2 diabetes mellitus, above glycemic target.",
        "plan": ["Increase metformin dose", "Dietitian referral", "Recheck HbA1c in three months", "Daily glucose monitoring"],
        "medications": [{"name": "Metformin", "dose": "1000 mg", "frequency": "twice daily"}],
        "cc": ("diabetes check-up", "more thirsty than usual and tired", "for the last month or so", "I take my metformin every day"),
    },
    {
        "code": "M54.50",
        "subjective": "Reports low back pain for one week after lifting boxes. Denies leg numbness, weakness, or bladder changes.",
        "objective": ["Lumbar paraspinal tenderness", "Straight leg raise negative", "Normal lower-extremity strength"],
        "assessment": "Acute mechanical low back pain without radiculopathy.",
        "plan": ["Ibuprofen for pain", "Stay active as tolerated", "Physical therapy referral", "Return if red-flag symptoms develop"],
        "medications": [{"name": "Ibuprofen", "dose": "400 mg", "frequency": "every 8 hours with food"}],
        "cc": ("back pain", "no numbness or weakness in my legs", "for about a week", "I hurt it lifting some boxes"),
    },
    {
        "code": "K21.9",
        "subjective": "Reports burning chest discomfort after meals and at night for several weeks, worse when lying down.",
        "objective": ["Abdomen soft, non-tender", "No epigastric mass", "Vitals within normal limits"],
        "assessment": "Gastro-esophageal reflux disease.",
        "plan": ["Start omeprazole", "Avoid late meals and trigger foods", "Elevate head of bed", "Follow up in six weeks"],
        "medications": [{"name": "Omeprazole", "dose": "20 mg", "frequency": "once daily before breakfast"}],
        "cc": ("heartburn", "burning in my chest after eating", "for a few weeks", "it's worse when I lie down"),
    },
]


@dataclass
class Encounter:
    encounter_id: str
    transcript: str
    gold_note: dict
    planted_phi: list[str]          # exact PHI strings injected (for leak eval)
    patient_name: str
    provider_name: str


def _build_transcript(fake: Faker, scenario: dict, patient: str, provider: str,
                      phi: dict) -> str:
    cc_main, cc_deny, cc_dur, cc_extra = scenario["cc"]
    meds = scenario["medications"]
    med = meds[0] if meds else None
    lines = [
        f"Provider: Good morning, I'm Dr. {provider.split()[-1]}. You're {patient}?",
        f"Patient: Yes, that's me. My MRN is {phi['mrn']} if you need it.",
        f"Provider: Thanks. And your date of birth?",
        f"Patient: {phi['dob']}. You can reach me at {phi['phone']} or {phi['email']}.",
        f"Provider: Great. What brings you in today?",
        f"Patient: I've had {cc_main}, {cc_extra}, {cc_dur}.",
        f"Provider: I see. Any other symptoms?",
        f"Patient: {cc_deny}.",
        f"Provider: Let me take a look and check your vitals.",
        f"Provider: {scenario['objective'][0]}, and {scenario['objective'][1].lower()}.",
        f"Provider: Based on this, it looks like {scenario['assessment'].lower()}",
    ]
    if med:
        lines.append(
            f"Provider: I'd like to start you on {med['name']} {med['dose']}, "
            f"{med['frequency']}."
        )
    lines.append(f"Patient: Okay, that sounds good. Anything else I should do?")
    lines.append(f"Provider: {scenario['plan'][0]}, and {scenario['plan'][-1].lower()}.")
    return "\n".join(lines)


def generate_encounter(seed: int) -> Encounter:
    """Generate one (transcript, gold_note, planted_phi) triple deterministically."""
    fake = Faker()
    Faker.seed(seed)
    random.seed(seed)

    scenario = SCENARIOS[seed % len(SCENARIOS)]
    patient = fake.name()
    provider = fake.name()

    phi = {
        "mrn": f"MRN {fake.numerify('#######')}",
        "dob": fake.date_of_birth(minimum_age=20, maximum_age=85).strftime("%m/%d/%Y"),
        "phone": fake.numerify("201-555-0###"),
        "email": fake.email(),
    }

    transcript = _build_transcript(fake, scenario, patient, provider, phi)

    gold_note = {
        "subjective": scenario["subjective"],
        "objective": list(scenario["objective"]),
        "assessment": scenario["assessment"],
        "plan": list(scenario["plan"]),
        "medications": [dict(m) for m in scenario["medications"]],
        "icd_candidates": [scenario["code"]],
    }

    planted_phi = [
        patient, provider,
        phi["mrn"], phi["mrn"].replace("MRN ", ""),
        phi["dob"], phi["phone"], phi["email"],
    ]

    return Encounter(
        encounter_id=f"enc_{seed:04d}",
        transcript=transcript,
        gold_note=gold_note,
        planted_phi=planted_phi,
        patient_name=patient,
        provider_name=provider,
    )


def generate_dataset(n: int) -> list[Encounter]:
    return [generate_encounter(seed=i) for i in range(n)]
